source 'https://rubygems.org'
gem 'cucumber'
gem 'faker'
gem 'nokogiri'
gem 'rspec'
gem 'cucumber-api'
gem 'test-unit'
gem 'minitest'
gem 'rest-client'
gem 'capybara'
gem 'rubocop'
gem 'yard'
gem "json_pure"
gem "cuke_sniffer"
gem "json"
gem "rake"
gem "yard-cucumber"
gem "redcarpet"
gem 'relish'
gem 'factory_girl'
gem 'rubocop-checkstyle_formatter'
gem 'wannabe_bool'
gem 'pry-rails'
gem 'pry-byebug'
gem 'require_all'
gem "haml"
gem "rdiscount"
gem "gherkin"
gem "gherkin3"
gem "komainu"
gem "mongo_mapper"
gem "bson_ext"
gem "fakefs"
gem "launchy"
gem "pretty_face"
